//------------------------------------------------------------------------------
// <auto-generated>
//     Esse código foi gerado por uma ferramenta.
//
//     As alterações no arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atlas.Api.ServiceReference.MotorRegras
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestResponseBase", Namespace="http://schemas.datacontract.org/2004/07/Omint.MotorRegras.Services.Domain.Request" +
        "Response")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Atlas.Api.ServiceReference.MotorRegras.ResponseBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Atlas.Api.ServiceReference.MotorRegras.ListarCamposRegrasResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Atlas.Api.ServiceReference.MotorRegras.ValidarRegistroResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Atlas.Api.ServiceReference.MotorRegras.RequestBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Atlas.Api.ServiceReference.MotorRegras.ValidarRegistroRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Atlas.Api.ServiceReference.MotorRegras.ListarCamposRegrasRequest))]
    public partial class RequestResponseBase : object
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.datacontract.org/2004/07/Omint.MotorRegras.Services.Domain.Request" +
        "Response")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Atlas.Api.ServiceReference.MotorRegras.ListarCamposRegrasResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Atlas.Api.ServiceReference.MotorRegras.ValidarRegistroResponse))]
    public partial class ResponseBase : Atlas.Api.ServiceReference.MotorRegras.RequestResponseBase
    {
        
        private string[] BusinessErrorsField;
        
        private bool IsValidField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] BusinessErrors
        {
            get
            {
                return this.BusinessErrorsField;
            }
            set
            {
                this.BusinessErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsValid
        {
            get
            {
                return this.IsValidField;
            }
            set
            {
                this.IsValidField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListarCamposRegrasResponse", Namespace="http://schemas.datacontract.org/2004/07/Omint.MotorRegras.Services.Domain.Request" +
        "Response.MotorRegras")]
    public partial class ListarCamposRegrasResponse : Atlas.Api.ServiceReference.MotorRegras.ResponseBase
    {
        
        private Atlas.Api.ServiceReference.MotorRegras.CampoRegrasDTO[] CamposRegraField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Atlas.Api.ServiceReference.MotorRegras.CampoRegrasDTO[] CamposRegra
        {
            get
            {
                return this.CamposRegraField;
            }
            set
            {
                this.CamposRegraField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidarRegistroResponse", Namespace="http://schemas.datacontract.org/2004/07/Omint.MotorRegras.Services.Domain.Request" +
        "Response.MotorRegras")]
    public partial class ValidarRegistroResponse : Atlas.Api.ServiceReference.MotorRegras.ResponseBase
    {
        
        private int CodigoRetornoValidacaoField;
        
        private Atlas.Api.ServiceReference.MotorRegras.CampoRegrasDTO[] ListaCamposValidacaoField;
        
        private Atlas.Api.ServiceReference.MotorRegras.RegraValidacaoDTO[] ListaRegrasValidacaoField;
        
        private bool RegistroValidadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRetornoValidacao
        {
            get
            {
                return this.CodigoRetornoValidacaoField;
            }
            set
            {
                this.CodigoRetornoValidacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Atlas.Api.ServiceReference.MotorRegras.CampoRegrasDTO[] ListaCamposValidacao
        {
            get
            {
                return this.ListaCamposValidacaoField;
            }
            set
            {
                this.ListaCamposValidacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Atlas.Api.ServiceReference.MotorRegras.RegraValidacaoDTO[] ListaRegrasValidacao
        {
            get
            {
                return this.ListaRegrasValidacaoField;
            }
            set
            {
                this.ListaRegrasValidacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RegistroValidado
        {
            get
            {
                return this.RegistroValidadoField;
            }
            set
            {
                this.RegistroValidadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://schemas.datacontract.org/2004/07/Omint.MotorRegras.Services.Domain.Request" +
        "Response")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Atlas.Api.ServiceReference.MotorRegras.ValidarRegistroRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Atlas.Api.ServiceReference.MotorRegras.ListarCamposRegrasRequest))]
    public partial class RequestBase : Atlas.Api.ServiceReference.MotorRegras.RequestResponseBase
    {
        
        private string LocaleField;
        
        private string PasswordField;
        
        private string UserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Locale
        {
            get
            {
                return this.LocaleField;
            }
            set
            {
                this.LocaleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidarRegistroRequest", Namespace="http://schemas.datacontract.org/2004/07/Omint.MotorRegras.Services.Domain.Request" +
        "Response.MotorRegras")]
    public partial class ValidarRegistroRequest : Atlas.Api.ServiceReference.MotorRegras.RequestBase
    {
        
        private Atlas.Api.ServiceReference.MotorRegras.CampoRegrasDTO[] CamposValidacaoField;
        
        private string CodigoIdentificacaoRegistroField;
        
        private string NomeGrupoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Atlas.Api.ServiceReference.MotorRegras.CampoRegrasDTO[] CamposValidacao
        {
            get
            {
                return this.CamposValidacaoField;
            }
            set
            {
                this.CamposValidacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoIdentificacaoRegistro
        {
            get
            {
                return this.CodigoIdentificacaoRegistroField;
            }
            set
            {
                this.CodigoIdentificacaoRegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeGrupo
        {
            get
            {
                return this.NomeGrupoField;
            }
            set
            {
                this.NomeGrupoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListarCamposRegrasRequest", Namespace="http://schemas.datacontract.org/2004/07/Omint.MotorRegras.Services.Domain.Request" +
        "Response.MotorRegras")]
    public partial class ListarCamposRegrasRequest : Atlas.Api.ServiceReference.MotorRegras.RequestBase
    {
        
        private string GrupoRegraField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GrupoRegra
        {
            get
            {
                return this.GrupoRegraField;
            }
            set
            {
                this.GrupoRegraField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CampoRegrasDTO", Namespace="http://schemas.datacontract.org/2004/07/Omint.MotorRegras.Services.Domain.Request" +
        "Response.Dto")]
    public partial class CampoRegrasDTO : object
    {
        
        private string DescricaoCampoField;
        
        private string GrupoServicoField;
        
        private string NomeCampoField;
        
        private bool ObrigatorioCampoField;
        
        private string RetornoValidacaoField;
        
        private string TipoCampoField;
        
        private string ValorCampoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoCampo
        {
            get
            {
                return this.DescricaoCampoField;
            }
            set
            {
                this.DescricaoCampoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GrupoServico
        {
            get
            {
                return this.GrupoServicoField;
            }
            set
            {
                this.GrupoServicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeCampo
        {
            get
            {
                return this.NomeCampoField;
            }
            set
            {
                this.NomeCampoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ObrigatorioCampo
        {
            get
            {
                return this.ObrigatorioCampoField;
            }
            set
            {
                this.ObrigatorioCampoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RetornoValidacao
        {
            get
            {
                return this.RetornoValidacaoField;
            }
            set
            {
                this.RetornoValidacaoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoCampo
        {
            get
            {
                return this.TipoCampoField;
            }
            set
            {
                this.TipoCampoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ValorCampo
        {
            get
            {
                return this.ValorCampoField;
            }
            set
            {
                this.ValorCampoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegraValidacaoDTO", Namespace="http://schemas.datacontract.org/2004/07/Omint.MotorRegras.Services.Domain.Request" +
        "Response.Dto")]
    public partial class RegraValidacaoDTO : object
    {
        
        private int CodigoRegraField;
        
        private string DescricaoRegraField;
        
        private string NomeRegraField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoRegra
        {
            get
            {
                return this.CodigoRegraField;
            }
            set
            {
                this.CodigoRegraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescricaoRegra
        {
            get
            {
                return this.DescricaoRegraField;
            }
            set
            {
                this.DescricaoRegraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomeRegra
        {
            get
            {
                return this.NomeRegraField;
            }
            set
            {
                this.NomeRegraField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Atlas.Api.ServiceReference.MotorRegras.IMotorRegrasService")]
    public interface IMotorRegrasService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotorRegrasService/ListarCamposRegra", ReplyAction="http://tempuri.org/IMotorRegrasService/ListarCamposRegraResponse")]
        System.Threading.Tasks.Task<Atlas.Api.ServiceReference.MotorRegras.ListarCamposRegrasResponse> ListarCamposRegraAsync(Atlas.Api.ServiceReference.MotorRegras.ListarCamposRegrasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMotorRegrasService/ValidarRegistro", ReplyAction="http://tempuri.org/IMotorRegrasService/ValidarRegistroResponse")]
        System.Threading.Tasks.Task<Atlas.Api.ServiceReference.MotorRegras.ValidarRegistroResponse> ValidarRegistroAsync(Atlas.Api.ServiceReference.MotorRegras.ValidarRegistroRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IMotorRegrasServiceChannel : Atlas.Api.ServiceReference.MotorRegras.IMotorRegrasService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class MotorRegrasServiceClient : System.ServiceModel.ClientBase<Atlas.Api.ServiceReference.MotorRegras.IMotorRegrasService>, Atlas.Api.ServiceReference.MotorRegras.IMotorRegrasService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar o ponto de extremidade de serviço.
        /// </summary>
        /// <param name="serviceEndpoint">O ponto de extremidade a ser configurado</param>
        /// <param name="clientCredentials">As credenciais do cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public MotorRegrasServiceClient() : 
                base(MotorRegrasServiceClient.GetDefaultBinding(), MotorRegrasServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CustomBinding_IMotorRegrasService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MotorRegrasServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(MotorRegrasServiceClient.GetBindingForEndpoint(endpointConfiguration), MotorRegrasServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MotorRegrasServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(MotorRegrasServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MotorRegrasServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(MotorRegrasServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public MotorRegrasServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Atlas.Api.ServiceReference.MotorRegras.ListarCamposRegrasResponse> ListarCamposRegraAsync(Atlas.Api.ServiceReference.MotorRegras.ListarCamposRegrasRequest request)
        {
            return base.Channel.ListarCamposRegraAsync(request);
        }
        
        public System.Threading.Tasks.Task<Atlas.Api.ServiceReference.MotorRegras.ValidarRegistroResponse> ValidarRegistroAsync(Atlas.Api.ServiceReference.MotorRegras.ValidarRegistroRequest request)
        {
            return base.Channel.ValidarRegistroAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_IMotorRegrasService))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                result.Elements.Add(new System.ServiceModel.Channels.BinaryMessageEncodingBindingElement());
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_IMotorRegrasService))
            {
                return new System.ServiceModel.EndpointAddress("http://p1.premiumassistance.com.br:91/MotorRegrasService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Não foi possível encontrar o ponto de extremidade com o nome \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return MotorRegrasServiceClient.GetBindingForEndpoint(EndpointConfiguration.CustomBinding_IMotorRegrasService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return MotorRegrasServiceClient.GetEndpointAddress(EndpointConfiguration.CustomBinding_IMotorRegrasService);
        }
        
        public enum EndpointConfiguration
        {
            
            CustomBinding_IMotorRegrasService,
        }
    }
}
